[app_node]
localhost ansible_port=2223 ansible_user=root ansible_ssh_pass=root ansible_connection=ssh

[monitor_node]
localhost ansible_port=2224 ansible_user=root ansible_ssh_pass=root ansible_connection=ssh